EcommerceP/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from accounts.views import register, MyLoginView,MyLogoutView
from Petsapp.views import pets_list


urlpatterns = [
    path('',pets_list,name='home'),
    path('admin/', admin.site.urls),
    path('petsapp/', include('Petsapp.urls')),
    path('register/',register,name='register-page'),
    path('login/',MyLoginView.as_view(template_name='base/login.html'), name='login'),
    path('logout/',MyLogoutView.as_view(),name='logout'),
    path('cart/', include('cart.urls'), name="cart"),
    path('orders/',include('orders.urls'), name="orders"),
]

if settings:
    urlpatterns+=static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import add_to_cart,cart_views1,delete_cart,update_cart

urlpatterns = [
    path('add_to_cart/<int:id>', add_to_cart, name="add_to_cart"),
    path('cart_view/',cart_views1, name='cart-view'),
    path('cart_delete/<int:id>/', delete_cart, name='deletecart'),
    path('updatecart/<int:id>/', update_cart,name='updatecart'),
]

orders/urls.py
from django.urls import path
from .import views
app_name = "orders"
urlpatterns = [
    path('order_billing/',views.place_order,name='order_billing'),
    path('payment/',views.payments,name='payments'),
]

cart/models.py
from django.db import models
from Petsapp.models import Pets
from django.contrib.auth.models import User

# Create your models here.

class cart(models.Model):
    cart_id = models.CharField(max_length=200, blank=True)
    pet = models.ForeignKey(Pets,on_delete=models.CASCADE)
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)
    totalprice = models.FloatField(default=0.00)
    timestamp = models.DateTimeField(auto_now_add=True)
    
    class Meta:
        db_table = 'cart_tbl' 
        

cart/views.py
from django.shortcuts import render, redirect
from .models import cart
from Petsapp.models import Pets
from django.contrib import messages
from django.http import JsonResponse

# Create your views here.

def add_to_cart(request,id):
    cart_id = request.session.session_key
    if cart_id == None:
        cart_id = request.session.create()
        
    
    pet_data = Pets.objects.get(id=id)
    price = pet_data.price
    user_data = request.user
    cart(cart_id = cart_id, pet = pet_data, user = user_data, totalprice = price).save()
    messages.success(request,"Item Added Successfully")
    return redirect('/')

def cart_views1(request):
    all_items = cart.objects.filter(user=request.user)
    flag = all_items.exists()
    return render(request,'cart/cart.html',{'items':all_items, 'flag':flag})

def delete_cart(request,id):
    cart_item_delete = cart.objects.get(id=id)
    cart_item_delete.delete()
    messages.success(request,'Item removed from cart successfully')
    return redirect('cart-view')

def update_cart(request,id):
    p = request.POST.get('price')
    q = request.POST.get('qty')
    p_id = request.POST.get('id')
    total_price = float(p) * int(q)
    cart.objects.filter(id=p_id).update(quantity=q, totalprice=total_price)
    return JsonResponse({'status': True, 'totalprice':total_price})

cart/templates/cart/cart.html
{% include 'base/header.html' %}
{% block content %}
  <form action="{% url 'orders:order_billing' %}">
  <table class="table table-striped">
    <thead>
      <th scope="col">Pet Name</th>
      <th scope="col">Quantity</th>
      <th scope="col">Price</th>
      <th scope="col">Total Price</th>
      <th scope="col">Action</th>
    </thead>
    {% if flag %}
      <tbody>
        {% for item in items %}
        <tr>
          <td><img src="{{ item.pet.image.url }}" width="100px" height="100px">
          <br/>
          <h4>{{ item.pet.name }}</h4>
          </td>
          <td>
            <input type="number" name="qty" min="0" value="{{ item.quantity }}"id="quantity{{ item.id }}" >
          </td>
          <td>
            {{ item.pet.price }}
          </td>
          <td>
            <input type="text" name="price" value="{{ item.totalprice }}" id="totalprice{{ item.id }}" readonly>
          </td>
          <td>
            <a href="{% url 'deletecart' item.id %}" class="btn btn-danger" data-id="{{ item.id }}">Delete</a>
          </td>
        </tr>
        {% endfor %}
      </tbody>

    {% else %}
        <h4>No item Added in Cart Yet</h4>
    {% endif %}
  </table>
   
      <h4>Total Amount : <span id="totalamount"></span></h4>

      <button type="submit">Proceed to Pay</button>
      
      </form>
    
  <script>
    $(document).ready(function(){
      $('form').submit(function(e){
        e.preventDefault(); // Preventing to submit the form
        var totalamount = parseFloat($("#totalamount").text()).toFixed(2);  // Total amount
        window.location.href = $(this).attr('action')+'?totalamount='+totalamount;
      });
      // localStorage.clear();
      $('input[name="qty"]').each(function(){
        var id = $(this).closest('tr').find('a').data('id');
        // alert(id);
        var price = $(this).closest('tr').find('td:nth-child(3)').text();
        var totalprice = parseFloat(price)*1;
        $("#totalprice"+id).val(totalprice.toFixed(2));
        $(this).val(1);

      });

      function CalculateTotalAmount(){
        var totalamount = 0;
        $('input[name="qty"]').each(function(){
             var id = $(this).closest('tr').find('a').data('id');
             var quantity = $(this).val();
             var price = $(this).closest('tr').find('td:nth-child(3)').text();
             var totalprice = parseFloat(price)*quantity;
             $("#totalprice"+id).val(totalprice.toFixed(2));
             totalamount += totalprice;
        });
        $("#totalamount").text(totalamount.toFixed(2));
      }

      $('input[name="qty"]').change(function(){
        var quantity = $(this).val();
        var price = $(this).closest('tr').find('td:nth-child(3)').text();
        var id = $(this).closest('tr').find('a').data('id');

        $.ajax({
          url : '/cart/updatecart/' + id + '/',
          method: 'POST',
          data: {'qty': quantity,'price': price, 'csrfmiddlewaretoken':'{{ csrf_token }}'},
          success:function(response){
            $("#totalprice"+ id).val(response.totalprice);
            CalculateTotalAmount();
            var totalamount = $("#totalamount").text();
            sessionStorage.setItem('total_amount',totalamount)   // Session Storage
          },
          error:function(){
              alert("Some Error In Code")
          }

        });
      
      });
      CalculateTotalAmount();
    });
  </script>
{% endblock %}
{% include 'base/footer.html' %}